export const outlay = [
    {id: 1, img: 'categories.png', name: 'all', spent: 0},
    {id: 2, img: 'shop.png', name: 'shops', spent: 0},
    {id: 3, img: 'present.png', name: 'present', spent: 0},
    {id: 4, img: 'wheel.png', name: 'fines', spent: 0},
    {id: 5, img: 'blouse.png', name: 'her clothes', spent: 0},
    {id: 6, img: 'book.png', name: 'books', spent: 0},
    {id: 7, img: 'bowling.png', name: 'playtime', spent: 0},
    {id: 8, img: 'theatre.png', name: 'theatre', spent: 0},
    {id: 9, img: 'boy_and_girl.png', name: 'kids', spent: 0},
    {id: 10, img: 'shoe.png', name: 'shoes', spent: 0},
    {id: 11, img: 'coffee.png', name: 'coffee', spent: 0},
    {id: 12, img: 'burger.png', name: 'fast food', spent: 0},
    {id: 13, img: 'service.png', name: 'service', spent: 0},
    {id: 14, img: 'bus.png', name: 'transport', spent: 0},
    {id: 15, img: 'car.png', name: 'car', spent: 0},
    {id: 16, img: 'cat.png', name: 'cat', spent: 0},
    {id: 17, img: 'apps.png', name: 'apps', spent: 0},
    {id: 18, img: 'cinema.png', name: 'cinema', spent: 0},
    {id: 19, img: 'clothes.png', name: 'his clothes', spent: 0},
    {id: 20, img: 'cocktail.png', name: 'cocktails', spent: 0},
    {id: 21, img: 'cosmetic.png', name: 'beauty', spent: 0},
    {id: 22, img: 'taxi.png', name: 'taxi', spent: 0},
    {id: 23, img: 'dog.png', name: 'dog', spent: 0},
    {id: 24, img: 'drinks.png', name: 'drinks/parties', spent: 0},
    {id: 25, img: 'electricity.png', name: 'household', spent: 0},
    {id: 26, img: 'family.png', name: 'family', spent: 0},
    {id: 27, img: 'star.png', name: 'favorite', spent: 0},
    {id: 28, img: 'food.png', name: 'food', spent: 0},
    {id: 29, img: 'fork_and_spoon.png', name: 'lunch', spent: 0},
    {id: 30, img: 'fuel.png', name: 'fuel', spent: 0},
    {id: 31, img: 'game.png', name: 'games', spent: 0},
    {id: 32, img: 'skier.png', name: 'active sport', spent: 0},
    {id: 33, img: 'sport.png', name: 'gym', spent: 0},
    {id: 34, img: 'hairdressing.png', name: 'hairdressing', spent: 0},
    {id: 35, img: 'heart.png', name: 'hobby', spent: 0},
    {id: 36, img: 'holidays.png', name: 'holidays', spent: 0},
    {id: 37, img: 'house.png', name: 'home', spent: 0},
    {id: 38, img: 'jet.png', name: 'trips', spent: 0},
    {id: 39, img: 'mail.png', name: 'internet', spent: 0},
    {id: 40, img: 'medcine.png', name: 'medcine', spent: 0},
    {id: 41, img: 'mobile.png', name: 'mobile', spent: 0},
    {id: 42, img: 'moneybox.png', name: 'moneybox', spent: 0},
    {id: 43, img: 'music.png', name: 'music', spent: 0},
    {id: 44, img: 'pipe.png', name: 'pipe', spent: 0},
    {id: 45, img: 'ring.png', name: 'jewellery', spent: 0},
]

export const profit = [
    {id: 1, img: 'clock.png', name: 'work', spent: 0},
    {id: 2, img: 'present.png', name: 'present', spent: 0},
    {id: 3, img: 'briefcase.png', name: 'business', spent: 0},
    {id: 4, img: 'bank.png', name: 'bank', spent: 0},
    {id: 5, img: 'repair.png', name: 'part-time job', spent: 0},
]